name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        # Provide dummy credentials for the config loader to pass during tests.
        # The actual tests mock the database connection, so these values are not used to connect.
        MSSQL_USER: testuser
        MSSQL_PASSWORD: testpassword
        MSSQL_DATABASE: testdb
